# Generated by Django 4.1 on 2022-09-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_skill_body_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbmail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
